-- Skrip DDL untuk Normalisasi Database Penjualan di Oracle 21

-- 1. Membuat Tabel Pelanggan
CREATE TABLE Pelanggan (
    pelanggan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_pelanggan VARCHAR2(100) NOT NULL,
    alamat VARCHAR2(255) NOT NULL,
    no_telp VARCHAR2(20) NOT NULL
);

-- 2. Membuat Tabel Produk
CREATE TABLE Produk (
    produk_id VARCHAR2(10) PRIMARY KEY,
    nama_produk VARCHAR2(150) NOT NULL,
    kategori VARCHAR2(100) NOT NULL,
    harga NUMBER(10,2) NOT NULL
);

-- 3. Membuat Tabel Pemesanan
CREATE TABLE Pemesanan (
    pemesanan_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pelanggan_id NUMBER NOT NULL,
    tanggal_pemesanan DATE NOT NULL,
    CONSTRAINT fk_pelanggan
        FOREIGN KEY (pelanggan_id)
        REFERENCES Pelanggan(pelanggan_id)
        ON DELETE CASCADE
);

-- 4. Membuat Tabel Detail_Pemesanan
CREATE TABLE Detail_Pemesanan (
    pemesanan_id NUMBER NOT NULL,
    produk_id VARCHAR2(10) NOT NULL,
    jumlah NUMBER(5) NOT NULL CHECK (jumlah > 0),
    PRIMARY KEY (pemesanan_id, produk_id),
    CONSTRAINT fk_pemesanan
        FOREIGN KEY (pemesanan_id)
        REFERENCES Pemesanan(pemesanan_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_produk
        FOREIGN KEY (produk_id)
        REFERENCES Produk(produk_id)
        ON DELETE RESTRICT
);

-- Indeks (Opsional)
-- Membuat indeks untuk kolom yang sering digunakan dalam query
CREATE INDEX idx_produk_kategori ON Produk(kategori);
CREATE INDEX idx_pemesanan_pelanggan ON Pemesanan(pelanggan_id);
CREATE INDEX idx_detail_pemesanan_produk ON Detail_Pemesanan(produk_id);