-- Skrip DDL untuk Normalisasi Database Perpustakaan di Oracle 21

-- 1. Membuat Tabel Kategori
CREATE TABLE Kategori (
    kategori VARCHAR2(50) PRIMARY KEY,
    deskripsi_kategori VARCHAR2(255) NOT NULL
);

-- 2. Membuat Tabel Anggota
CREATE TABLE Anggota (
    anggota_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama_anggota VARCHAR2(100) NOT NULL,
    alamat VARCHAR2(255) NOT NULL,
    no_telp VARCHAR2(20) NOT NULL
);

-- 3. Membuat Tabel Buku
CREATE TABLE Buku (
    buku_id VARCHAR2(10) PRIMARY KEY,
    judul_buku VARCHAR2(150) NOT NULL,
    pengarang VARCHAR2(100) NOT NULL,
    penerbit VARCHAR2(100) NOT NULL,
    kategori VARCHAR2(50) NOT NULL,
    CONSTRAINT fk_kategori
        FOREIGN KEY (kategori)
        REFERENCES Kategori(kategori)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- 4. Membuat Tabel Peminjaman
CREATE TABLE Peminjaman (
    peminjaman_id VARCHAR2(10) PRIMARY KEY,
    anggota_id NUMBER NOT NULL,
    tanggal_pinjam DATE NOT NULL,
    tanggal_kembali DATE NOT NULL,
    CONSTRAINT fk_anggota
        FOREIGN KEY (anggota_id)
        REFERENCES Anggota(anggota_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- 5. Membuat Tabel Detail_Peminjaman
CREATE TABLE Detail_Peminjaman (
    peminjaman_id VARCHAR2(10) NOT NULL,
    buku_id VARCHAR2(10) NOT NULL,
    jumlah NUMBER(5) NOT NULL CHECK (jumlah > 0),
    PRIMARY KEY (peminjaman_id, buku_id),
    CONSTRAINT fk_peminjaman
        FOREIGN KEY (peminjaman_id)
        REFERENCES Peminjaman(peminjaman_id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_buku
        FOREIGN KEY (buku_id)
        REFERENCES Buku(buku_id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- Indeks (Opsional)
-- Membuat indeks untuk kolom yang sering digunakan dalam query
CREATE INDEX idx_buku_kategori ON Buku(kategori);
CREATE INDEX idx_peminjaman_anggota ON Peminjaman(anggota_id);
CREATE INDEX idx_detail_peminjaman_buku ON Detail_Peminjaman(buku_id);